/*
 * Swagger Petstore
 * A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pro.keenetic.okoswaroga.api.entity.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * NewPet
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-05T22:25:43.411501300+03:00[Europe/Helsinki]")
public class NewPet {
  @SerializedName("name")
  private String name = null;

  @SerializedName("tag")
  private String tag = null;

  /**
   * Name new pet.
   *
   * @param name the name
   * @return the new pet
   */
  public NewPet name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name name
   */
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  /**
   * Sets name.
   *
   * @param name the name
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Tag new pet.
   *
   * @param tag the tag
   * @return the new pet
   */
  public NewPet tag(String tag) {
    this.tag = tag;
    return this;
  }

  /**
   * Get tag
   *
   * @return tag tag
   */
  @Schema(description = "")
  public String getTag() {
    return tag;
  }

  /**
   * Sets tag.
   *
   * @param tag the tag
   */
  public void setTag(String tag) {
    this.tag = tag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewPet newPet = (NewPet) o;
    return Objects.equals(this.name, newPet.name) &&
        Objects.equals(this.tag, newPet.tag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, tag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewPet {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * The type New pet builder.
   */
  public static final class NewPetBuilder {
    private NewPet newPet;

    private NewPetBuilder() {
      newPet = new NewPet();
    }

    /**
     * A new pet new pet builder.
     *
     * @return the new pet builder
     */
    public static NewPetBuilder aNewPet() {
      return new NewPetBuilder();
    }

    /**
     * With name new pet builder.
     *
     * @param name the name
     * @return the new pet builder
     */
    public NewPetBuilder withName(String name) {
      newPet.setName(name);
      return this;
    }

    /**
     * With tag new pet builder.
     *
     * @param tag the tag
     * @return the new pet builder
     */
    public NewPetBuilder withTag(String tag) {
      newPet.setTag(tag);
      return this;
    }

    /**
     * Build new pet.
     *
     * @return the new pet
     */
    public NewPet build() {
      return newPet;
    }
  }
}
